### ISSUE TITLE
Limit of saved tabs in 1200

### ISSUE THREAD

**Issue by renanoliveira0** [joelpt/sidewise#62]
After ~1200 tabs, my extension always with Chrome close, lost 100+ tabs.

**Comment by Nao** [comment]
For more it's about 2000 tabs. After which I completely lose everything upon restart (the sidewise window is empty), which forces me to back up my sessions just to be sure I can at least go back to a session that had less than 2000 tabs. Complicated, but hey, the alternative is no Sidewise at all... :)

**Comment by renanoliveira0** [comment]
When this guy is make the project open source for we help build and fix issues like this?

**Comment by Nao** [comment]
Well it's not open source, but you can always view the source code... Just find the proper folder in your Chrome profile, then you'll have access to all the JS files. You can prettify them (and make them readable) with plenty of web tools. Then you can mod them. Personally, I've modded the window manager to increase the width so that the scrollbar is partly outside the screen (giving me a few more px of screen estate, among other advantages.)

**Comment by joelpt** [comment]
The data corruption issues surrounding having several thousand tabs should now be fixed. Sidewise should now be able to store an essentially unlimited number of tabs. It is now using chrome.storage.local for storing the tree data, which has no maximum storage limit.

Please let me know if you see any further issues of this type.

**Comment by renanoliveira0** [comment]
OK! Thanks very much!!!
